@baseUrl = http://localhost:3000/api
@module = auth
@email = {{$dotenv AUTH_EMAIL}}
@password = {{$dotenv AUTH_PASSWORD}}

### Login

# @name login
# -- @prompt email
POST {{baseUrl}}/{{module}}/login
Content-Type: application/json

{
  "email": "{{ email }}",
  "password": "{{password}}"
}

@token = {{ login.response.body.token }}

### User data (requires token)
# Returns user info with groups and selectedGroup (from cookie)

# @name me
GET {{baseUrl}}/{{module}}/me
Authorization: Bearer {{token}}

### Permissions (requires token)

# @name get-permissions
GET {{baseUrl}}/{{module}}/permissions
Authorization: Bearer {{token}}

### Logout

# @name logout
POST {{baseUrl}}/{{module}}/logout
Authorization: Bearer {{token}}

### Get Token from Cookie

# @name get-token
GET {{baseUrl}}/{{module}}/token

### Get Group from Cookie

# @name get-group
GET {{baseUrl}}/{{module}}/group
