@baseUrl = http://localhost:3000/api
@module = 'permissions'
@name = 'test.permission.tmp'
@description = 'Test Permission'
@id = 1

###

GET {{baseUrl}}/{{module}}

###

POST {{baseUrl}}/{{module}}
Content-Type: application/json

{
  "name": "{{name}}",
  "description": "{{description}}"
}

###

GET {{baseUrl}}/{{module}}/{{id}}

###

PUT {{baseUrl}}/{{module}}/{{id}}
Content-Type: application/json

{
  "name": "{{name}}.updated",
  "description": "{{description}} Updated"
}

###

DELETE {{baseUrl}}/{{module}}/{{id}}
