@baseUrl = http://localhost:3000/api
@module = permissions
@name = test.permission.http
@description = A temporary permission for http tests
@id = 1

###
# @name Get all permissions
GET {{baseUrl}}/{{module}}

###
# @name Create a new permission
POST {{baseUrl}}/{{module}}
Content-Type: application/json

{
  "name": "{{name}}",
  "description": "{{description}}"
}

###
# @name Get permission by id
GET {{baseUrl}}/{{module}}/{{id}}

###
# @name Update a permission
PUT {{baseUrl}}/{{module}}/{{id}}
Content-Type: application/json

{
  "name": "{{name}}.updated",
  "description": "{{description}} Updated"
}

###
# @name Delete a permission
DELETE {{baseUrl}}/{{module}}/{{id}}
