export enum DocumentStatus {
  DRAFT = 'draft',
  UPLOADED = 'uploaded',
  IN_REVIEW = 'in_review',
  PENDING_NOTIFICATION = 'pending_notification',
  IN_REVIEW_FOR_SIGN = 'in_review_for_sign',
  IN_SIGNING = 'in_signing',
  APPROVED = 'approved',
  SIGNED = 'signed',
  REJECTED = 'rejected',
  REJECTED_WITH_COMMENTS = 'rejected_with_comments',
  REJECTED_FOR_SIGN = 'rejected_for_sign',
  EXPIRED = 'expired',
  OBSOLETE = 'obsolete',
  ARCHIVED = 'archived',
  SIGNATURE_CLOSED = 'signature_closed',
}

export enum DocumentAction {
  CREATED = 'created',
  UPDATED = 'updated',
  SUBMITTED_FOR_REVIEW = 'submitted_for_review',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  REJECTED_WITH_COMMENTS = 'rejected_with_comments',
  ARCHIVED = 'archived',
  RESTORED = 'restored',
  SIGNATURE_INITIATED = 'signature_initiated',
  SIGNATURE_SIGNED = 'signature_signed',
  SIGNATURE_REJECTED = 'signature_rejected',
  SIGNATURE_ERROR = 'signature_error',
  SIGNATURE_REJECTED_CANCELLED_BY_USER = 'signature_rejected_cancelled_by_user',
  SIGNATURE_REJECTED_TIMEOUT = 'signature_rejected_timeout',
  SIGNATURE_REJECTED_MAX_ATTEMPTS = 'signature_rejected_max_attempts',
  FLOW_SENT = 'flow_sent',
  FLOW_VALIDATED = 'flow_validated',
  FLOW_REJECTED = 'flow_rejected',
  FLOW_SIGNED = 'flow_signed',
  FLOW_PARTICIPANT_REJECTED = 'flow_participant_rejected',
  FLOW_PARTICIPANT_SKIPPED = 'flow_participant_skipped',
  FLOW_CLOSED = 'flow_closed',
  FLOW_REOPENED = 'flow_reopened',
  FLOW_COMPLETED = 'flow_completed',
  VERSION_SUPERSEDED = 'version_superseded',
  NOTIFICATION_ERROR = 'notification_error',
}
